// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
	// Generates a sidebar from the docs folder structure
	tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
